In [16]:
# numpy =  consist of array which arrray helps to braodcast,vectorizzation,mathematic operation
#pandas  = allows to create tables,manipulate,load external data rather than matrix

In [17]:
#pandas is library for creating series and datafrma(table data)
#it allow as to load read,write modify csv,excel,json etc files 
# it uses 2 data structure: 1) series: 1D labelled data(like single column with column name)
                            #2) dataframe: 2D labelled data(table having multiple rows and columns)

In [18]:
# !pip install pandas

In [19]:
import pandas as pd

In [20]:
# creating data with pandas

In [21]:
data = {
    'Name': ['Binod','Naveen', 'Gourav','Aakash','Madina'],
    'Age': [24,20,19,19,18]
}
data

{'Name': ['Binod', 'Naveen', 'Gourav', 'Aakash', 'Madina'],
 'Age': [24, 20, 19, 19, 18]}

In [22]:
df=pd.DataFrame(data)

In [23]:
print(df)

     Name  Age
0   Binod   24
1  Naveen   20
2  Gourav   19
3  Aakash   19
4  Madina   18

In [24]:
df['Age']

0    24
1    20
2    19
3    19
4    18
Name: Age, dtype: int64

In [25]:
df['Name']

0     Binod
1    Naveen
2    Gourav
3    Aakash
4    Madina
Name: Name, dtype: object

In [26]:
#df=pd.DataFrame(data,index=['A','B','C','D','E'])
#df

In [27]:
# to access rows we can use 2 method
#1) loc: labeled based
#2) iloc : index based

In [37]:
df.loc[1,'Age'] #[rows,column]

np.int64(20)

In [38]:
print(df.loc[1,'Age'])

20

In [39]:
df.iloc[1,1]# instead of [passing label i have to pass index]

np.int64(20)

In [40]:
# how to load dataset

#df=pd.read_csv("path")
#df

In [41]:
import seaborn as sns

In [42]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [43]:
df=sns.load_dataset('iris')

In [44]:
df.head()# gives first 5 rows
df.tail()
df.head(10)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa

In [45]:
#.shape -> attribute used for getting numers of record and features
a=df.shape
print(a)

print(f"Rows: {a[0]}, Columns: {a[1]}")

(150, 5)
Rows: 150, Columns: 5

In [46]:
df.info()# gives brief summary

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [47]:
# check null values
df.isnull() # or. isna

     sepal_length  sepal_width  petal_length  petal_width  species
0           False        False         False        False    False
1           False        False         False        False    False
2           False        False         False        False    False
3           False        False         False        False    False
4           False        False         False        False    False
..            ...          ...           ...          ...      ...
145         False        False         False        False    False
146         False        False         False        False    False
147         False        False         False        False    False
148         False        False         False        False    False
149         False        False         False        False    False

[150 rows x 5 columns]

In [48]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [ ]:
# if we haev null values : we can drop this null values by 'df.dropna'
# if you want to fill null values use 'df.fillna()

In [49]:
# describe() -> it gives statistical summary
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [50]:
df.describe().T # transpose

              count      mean       std  min  25%   50%  75%  max
sepal_length  150.0  5.843333  0.828066  4.3  5.1  5.80  6.4  7.9
sepal_width   150.0  3.057333  0.435866  2.0  2.8  3.00  3.3  4.4
petal_length  150.0  3.758000  1.765298  1.0  1.6  4.35  5.1  6.9
petal_width   150.0  1.199333  0.762238  0.1  0.3  1.30  1.8  2.5

In [ ]:
df.describe(include='all').T # only des gives info about numeric values include ='all' gives value of whole table

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
sepal_length,150.0,NaN,NaN,NaN,5.843333,0.828066,4.3,5.1,5.8,6.4,7.9
sepal_width,150.0,NaN,NaN,NaN,3.057333,0.435866,2.0,2.8,3.0,3.3,4.4
petal_length,150.0,NaN,NaN,NaN,3.758,1.765298,1.0,1.6,4.35,5.1,6.9
petal_width,150.0,NaN,NaN,NaN,1.199333,0.762238,0.1,0.3,1.3,1.8,2.5
species,150,3,setosa,50,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#std deviation means how much data is spread around mean

In [ ]:
# how to filter data

In [55]:
# filter data baes on condition
df.head()
# i want to [print values where sepal lenth >6]

df[df['sepal_length'] > 6.0]

     sepal_length  sepal_width  petal_length  petal_width     species
50            7.0          3.2           4.7          1.4  versicolor
51            6.4          3.2           4.5          1.5  versicolor
52            6.9          3.1           4.9          1.5  versicolor
54            6.5          2.8           4.6          1.5  versicolor
56            6.3          3.3           4.7          1.6  versicolor
..            ...          ...           ...          ...         ...
144           6.7          3.3           5.7          2.5   virginica
145           6.7          3.0           5.2          2.3   virginica
146           6.3          2.5           5.0          1.9   virginica
147           6.5          3.0           5.2          2.0   virginica
148           6.2          3.4           5.4          2.3   virginica

[61 rows x 5 columns]

In [58]:
x=df[(df['petal_length']>6) & (df['petal_length']<7)]
print(x)

     sepal_length  sepal_width  petal_length  petal_width    species
105           7.6          3.0           6.6          2.1  virginica
107           7.3          2.9           6.3          1.8  virginica
109           7.2          3.6           6.1          2.5  virginica
117           7.7          3.8           6.7          2.2  virginica
118           7.7          2.6           6.9          2.3  virginica
122           7.7          2.8           6.7          2.0  virginica
130           7.4          2.8           6.1          1.9  virginica
131           7.9          3.8           6.4          2.0  virginica
135           7.7          3.0           6.1          2.3  virginica

In [59]:
# how to modify existing data
x['petal_length']= x['petal_length'] + 1
x

C:\Users\DELL\AppData\Local\Temp\ipykernel_19104\1081851870.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['petal_length']= x['petal_length'] + 1

     sepal_length  sepal_width  petal_length  petal_width    species
105           7.6          3.0           7.6          2.1  virginica
107           7.3          2.9           7.3          1.8  virginica
109           7.2          3.6           7.1          2.5  virginica
117           7.7          3.8           7.7          2.2  virginica
118           7.7          2.6           7.9          2.3  virginica
122           7.7          2.8           7.7          2.0  virginica
130           7.4          2.8           7.1          1.9  virginica
131           7.9          3.8           7.4          2.0  virginica
135           7.7          3.0           7.1          2.3  virginica

In [61]:
#create nwe column
df['newcol'] = df['sepal_length'] * 10
df.head()

   sepal_length  sepal_width  petal_length  petal_width species  newcol
0           5.1          3.5           1.4          0.2  setosa    51.0
1           4.9          3.0           1.4          0.2  setosa    49.0
2           4.7          3.2           1.3          0.2  setosa    47.0
3           4.6          3.1           1.5          0.2  setosa    46.0
4           5.0          3.6           1.4          0.2  setosa    50.0

In [62]:
#rename column
df.rename(columns={'newcol': 'updated column'},inplace=True) # inpace true means changes are getting saves
df.head()

,sepal_length,sepal_width,petal_length,petal_width,species,updated column
0,5.1,3.5,1.4,0.2,setosa,51.0
1,4.9,3.0,1.4,0.2,setosa,49.0
2,4.7,3.2,1.3,0.2,setosa,47.0
3,4.6,3.1,1.5,0.2,setosa,46.0
4,5.0,3.6,1.4,0.2,setosa,50.0

In [63]:
# to check duplicates values 
df.duplicated()
df.duplicated().sum()

np.int64(1)

In [64]:
#to remove duplicated values
df.drop_duplicates(inplace = True)
df.shape

(149, 6)

In [65]:
tips =sns.load_dataset('tips')
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [66]:
tips.shape # shape is attribute so no need of ()
tips.ndim # atrriburte

2

In [67]:
tips.info() # methods have parenthesis

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [68]:
# value count
tips['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64